.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH waka-report 1  "report " 
.SH NAME
waka\-report \- Generate productivity reports
.SH SYNOPSIS
\fBwaka report\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIsubcommands\fR]
.SH DESCRIPTION
Generate productivity reports
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
waka\-report\-generate(1)
Generate a report for a date range
.TP
waka\-report\-summary(1)
Show a brief productivity summary
