.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH waka-leaderboard 1  "leaderboard " 
.SH NAME
waka\-leaderboard \- View the WakaTime leaderboard
.SH SYNOPSIS
\fBwaka leaderboard\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIsubcommands\fR]
.SH DESCRIPTION
View the WakaTime leaderboard
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
waka\-leaderboard\-show(1)
Show the public leaderboard
