.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH waka-stats 1  "stats " 
.SH NAME
waka\-stats \- Show coding statistics
.SH SYNOPSIS
\fBwaka stats\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIsubcommands\fR]
.SH DESCRIPTION
Show coding statistics
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
waka\-stats\-today(1)
Show today\*(Aqs coding stats
.TP
waka\-stats\-yesterday(1)
Show yesterday\*(Aqs coding stats
.TP
waka\-stats\-week(1)
Show stats for the last 7 days
.TP
waka\-stats\-month(1)
Show stats for the last 30 days
.TP
waka\-stats\-year(1)
Show stats for the last 365 days
.TP
waka\-stats\-all\-time(1)
Show all\-time coding stats
.TP
waka\-stats\-range(1)
Show stats for a custom date range
