.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH waka-auth-whoami 1  "whoami " 
.SH NAME
waka\-auth\-whoami \- Display the authenticated user info
.SH SYNOPSIS
\fBwaka auth whoami\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Display the authenticated user info
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
