.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH waka-changelog 1  "changelog " 
.SH NAME
waka\-changelog \- Show the changelog from the installed version to the latest
.SH SYNOPSIS
\fBwaka changelog\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Show the changelog from the installed version to the latest
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
