.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH waka-report-summary 1  "summary " 
.SH NAME
waka\-report\-summary \- Show a brief productivity summary
.SH SYNOPSIS
\fBwaka report summary\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Show a brief productivity summary
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
