.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH waka-config-reset 1  "reset " 
.SH NAME
waka\-config\-reset \- Reset configuration to defaults
.SH SYNOPSIS
\fBwaka config reset\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Reset configuration to defaults
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
