.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH waka-stats-all-time 1  "all-time " 
.SH NAME
waka\-stats\-all\-time \- Show all\-time coding stats
.SH SYNOPSIS
\fBwaka stats all\-time\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Show all\-time coding stats
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
