.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH waka-cache 1  "cache " 
.SH NAME
waka\-cache \- Manage the local response cache
.SH SYNOPSIS
\fBwaka cache\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIsubcommands\fR]
.SH DESCRIPTION
Manage the local response cache
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
waka\-cache\-clear(1)
Clear all cached data
.TP
waka\-cache\-info(1)
Show cache statistics
.TP
waka\-cache\-path(1)
Print the cache directory path
