.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH waka-stats-range 1  "range " 
.SH NAME
waka\-stats\-range \- Show stats for a custom date range
.SH SYNOPSIS
\fBwaka stats range\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Show stats for a custom date range
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
