.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH waka-projects 1  "projects " 
.SH NAME
waka\-projects \- Browse and filter projects
.SH SYNOPSIS
\fBwaka projects\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIsubcommands\fR]
.SH DESCRIPTION
Browse and filter projects
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
waka\-projects\-list(1)
List all projects
.TP
waka\-projects\-top(1)
Show top projects by time coded
