.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH waka-stats-yesterday 1  "yesterday " 
.SH NAME
waka\-stats\-yesterday \- Show yesterday\*(Aqs coding stats
.SH SYNOPSIS
\fBwaka stats yesterday\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Show yesterday\*(Aqs coding stats
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
