.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH waka-report-generate 1  "generate " 
.SH NAME
waka\-report\-generate \- Generate a report for a date range
.SH SYNOPSIS
\fBwaka report generate\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Generate a report for a date range
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
