.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH waka-leaderboard-show 1  "show " 
.SH NAME
waka\-leaderboard\-show \- Show the public leaderboard
.SH SYNOPSIS
\fBwaka leaderboard show\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Show the public leaderboard
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
