.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH waka-languages-top 1  "top " 
.SH NAME
waka\-languages\-top \- Show top languages by time coded
.SH SYNOPSIS
\fBwaka languages top\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Show top languages by time coded
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
