.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH waka-languages 1  "languages " 
.SH NAME
waka\-languages \- Browse coding languages
.SH SYNOPSIS
\fBwaka languages\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIsubcommands\fR]
.SH DESCRIPTION
Browse coding languages
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
waka\-languages\-list(1)
List all languages
.TP
waka\-languages\-top(1)
Show top languages by time coded
