.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH waka-auth-status 1  "status " 
.SH NAME
waka\-auth\-status \- Show current authentication status
.SH SYNOPSIS
\fBwaka auth status\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Show current authentication status
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
