.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH waka-prompt 1  "prompt " 
.SH NAME
waka\-prompt \- Shell prompt integration (reads from cache only, no network)
.SH SYNOPSIS
\fBwaka prompt\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Shell prompt integration (reads from cache only, no network)
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
