.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH waka-dashboard 1  "dashboard " 
.SH NAME
waka\-dashboard \- Launch the interactive TUI dashboard
.SH SYNOPSIS
\fBwaka dashboard\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Launch the interactive TUI dashboard
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
